### ISSUE TITLE
Bug looping 

### ISSUE THREAD

**Issue by danilo-alm** [guilherme-gjv/As-5-Regioes-do-Brasil#2]
Na parte "vamos falar sobre as regiões do Brasil?", logo no início, se você responder à pergunta com uma letra, o código entra em looping e buga 👍

**Comment by guilherme-gjv** [comment]
Dá uma olhada agora

**Comment by guilherme-gjv** [comment]
Agora sim descobri o verdadeiro problema: ele tava bugando o buffer.
Por isso, adicionei a função fflush(stdin) que limpa o buffer caso seja digitado algum valor menor que 1, aí dá pra substituir o valor da variável quando antes só entrava no looping :)
